services:
  postgres:
    image: 'postgres:17'
    environment:
      - 'POSTGRES_DB=marketplace'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - target: 5432
        published: 5488
